[package]
name = "todo"
version = "2.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "~0.26"
clap = { version = "3.1.18", features = ["derive"] }
lazy_static = "1.4.0"
